spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_caso_autoservicio
    username: root
    password: jardiN2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect